# Generated by Django 4.2.1 on 2023-11-02 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=100)),
                (
                    "academic_units",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_schedule",
                    models.CharField(
                        max_length=38,
                        validators=[
                            modsoptimizer.utils.validation.validate_exam_schedule
                        ],
                    ),
                ),
                (
                    "common_schedule",
                    models.CharField(
                        max_length=192,
                        validators=[
                            modsoptimizer.utils.validation.validate_weekly_schedule
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.CharField(max_length=5, unique=True)),
                ("information", models.TextField()),
                (
                    "schedule",
                    models.CharField(
                        max_length=192,
                        validators=[
                            modsoptimizer.utils.validation.validate_weekly_schedule
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexes",
                        to="modsoptimizer.coursecode",
                    ),
                ),
            ],
        ),
    ]
