# Generated by Django 4.2.1 on 2023-11-22 11:36

import django.core.validators
from django.db import migrations, models
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursecode",
            options={"verbose_name_plural": "Course Codes"},
        ),
        migrations.AlterModelOptions(
            name="courseindex",
            options={"verbose_name_plural": "Course Indexes"},
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="code",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="exam_schedule",
            field=models.CharField(
                blank=True,
                max_length=38,
                validators=[modsoptimizer.utils.validation.validate_exam_schedule],
            ),
        ),
        migrations.AlterField(
            model_name="courseindex",
            name="index",
            field=models.CharField(
                max_length=5,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_format",
                        message="The value must be 5 numeric digits.",
                        regex="^\\d{5}$",
                    )
                ],
            ),
        ),
    ]
