# Generated by Django 4.2.1 on 2023-12-10 09:38

from django.db import migrations, models
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    dependencies = [
        (
            "modsoptimizer",
            "0002_alter_coursecode_options_alter_courseindex_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecode",
            name="exam_schedule",
            field=models.CharField(
                blank=True,
                max_length=42,
                validators=[modsoptimizer.utils.validation.validate_exam_schedule],
            ),
        ),
    ]
