# Generated by Django 4.2.1 on 2023-12-30 07:42

from django.db import migrations, models
import modsoptimizer.utils.validation


class Migration(migrations.Migration):

    dependencies = [
        ("modsoptimizer", "0003_alter_coursecode_exam_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="common_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseindex",
            name="filtered_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="exam_schedule",
            field=models.CharField(
                blank=True,
                max_length=53,
                validators=[modsoptimizer.utils.validation.validate_exam_schedule],
            ),
        ),
    ]
