# Generated by Django 4.2.1 on 2023-06-24 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexswapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="contact_info",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
