# Generated by Django 4.2.1 on 2023-07-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexswapper", "0003_swaprequest_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="swaprequest",
            name="index_gained",
            field=models.CharField(default="", max_length=6),
        ),
    ]
