# Generated by Django 4.2.1 on 2023-07-05 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexswapper", "0008_alter_swaprequest_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseindex",
            name="pending_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
