# Generated by Django 4.2.1 on 2023-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexswapper", "0009_alter_courseindex_pending_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Searching"),
                    ("W", "Waiting"),
                    ("C", "Completed"),
                    ("R", "Revoked"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
