# Generated by Django 4.2.1 on 2023-07-06 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_token",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(default="default_name", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="token_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
